"""STS RL 项目的公开 Python 接口。"""

from sts.agents import (
    Agent,
    AgentDecision,
    EpisodeTrace,
    MaskedRandomAgent,
    decode_agent_decision,
    masked_softmax,
    run_episode,
)
from sts.env import (
    DEFAULT_CARD_REGISTRY,
    PAD_ID,
    REGISTRY_VERSION,
    SCHEMA_VERSION,
    CardDefinition,
    CardLocation,
    CardObservation,
    CardRegistry,
    Encounter,
    FlatInput,
    FlattenWrapper,
    LightspeedBattleEnv,
    Observation,
    TargetKind,
    TokenInput,
    TokenWrapper,
)
from sts.rewards import (
    BATTLE_REWARD_CONTRACT,
    BATTLE_REWARD_VERSION,
    RUN_REWARD_VERSION,
    RewardContract,
    battle_step_reward,
    make_run_reward_contract,
    recompute_episode_reward_and_rtg,
    run_step_reward,
    true_return_to_go,
)

__all__ = [
    "BATTLE_REWARD_CONTRACT",
    "BATTLE_REWARD_VERSION",
    "DEFAULT_CARD_REGISTRY",
    "PAD_ID",
    "REGISTRY_VERSION",
    "RUN_REWARD_VERSION",
    "SCHEMA_VERSION",
    "Agent",
    "AgentDecision",
    "CardDefinition",
    "CardLocation",
    "CardObservation",
    "CardRegistry",
    "Encounter",
    "EpisodeTrace",
    "FlatInput",
    "FlattenWrapper",
    "LightspeedBattleEnv",
    "MaskedRandomAgent",
    "Observation",
    "RewardContract",
    "TargetKind",
    "TokenInput",
    "TokenWrapper",
    "battle_step_reward",
    "decode_agent_decision",
    "make_run_reward_contract",
    "masked_softmax",
    "recompute_episode_reward_and_rtg",
    "run_episode",
    "run_step_reward",
    "true_return_to_go",
]
